name: ohw20-proj-argo-mapping
channels:
  - conda-forge
dependencies:
  - xarray
  - dask
  - scikit-learn
  - matplotlib
  - cartopy
  - seaborn
  - george
  - jupyterlab
  - argopy
  - scipy
  - requests
  - aiohttp
  - cmocean
